from pydantic import BaseModel, Field, field_validator, ConfigDict
from typing import List, Optional
from datetime import datetime
from enum import Enum
import json



# Recipe Model for structured output
class DifficultyLevel(str, Enum):
    """Recipe difficulty levels"""
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"

class CuisineType(str, Enum):
    AMERICAN = "american"
    ITALIAN = "italian"
    MEXICAN = "mexican"
    CHINESE = "chinese"
    JAPANESE = "japanese"
    INDIAN = "indian"
    THAI = "thai"
    FRENCH = "french"
    MEDITERRANEAN = "mediterranean"
    GREEK = "greek"
    MIDDLE_EASTERN = "middle_eastern"
    SPANISH = "spanish"
    RUSSIAN = "russian"
    KOREAN = "korean"
    ETHIOPIAN = "ethiopian"
    PERUVIAN = "peruvian"
    MOROCCAN = "moroccan"
    OTHER = "other"

class MealType(str, Enum):
    """Meal categories"""
    BREAKFAST = "breakfast"
    LUNCH = "lunch"
    DINNER = "dinner"
    SNACK = "snack"
    DESSERT = "dessert"
    APPETIZER = "appetizer"

class Ingredient(BaseModel):
    """Individual ingredient in a recipe"""
    name: str = Field(..., description="Name of the ingredient")
    quantity: float = Field(..., description="Amount needed", gt=0)
    unit: str = Field(..., description="Unit of measurement (e.g., cups, tbsp, lbs, count)")
    notes: Optional[str] = Field(None, description="Additional notes (e.g., 'chopped', 'diced', 'to taste')")
    optional: bool = Field(default=False, description="Whether this ingredient is optional")
    location: Optional[str] = Field(
        None,
        description="Where this ingredient is stored: 'fridge' (dairy, fresh produce, eggs, meats, leftovers), "
                    "'freezer' (frozen meats, frozen vegetables, ice cream), "
                    "'pantry' (canned goods, grains, oils, flour, sugar, shelf-stable items), "
                    "or 'spices' (dried herbs, spices, seasoning blends)"
    )
    category: Optional[str] = Field(
        None,
        description="Pantry category: one of 'Produce', 'Dairy & Eggs', 'Meat & Seafood', "
                    "'Grains & Bread', 'Pantry Staples', 'Beverages', 'Other'"
    )

class RecipeStep(BaseModel):
    """Individual step in recipe instructions"""
    step_number: int = Field(..., description="Order of the step", ge=1)
    instruction: str = Field(..., description="Detailed instruction for this step")

class Recipe(BaseModel):
    """Complete recipe generated by LLM"""
    title: str = Field(..., description="Recipe name/title")
    description: str = Field(..., description="Brief description of the dish")
    cuisine: CuisineType = Field(..., description="Type of cuisine")
    meal_type: MealType = Field(..., description="Type of meal")
    difficulty: DifficultyLevel = Field(..., description="Difficulty level")
    
    # Time information
    prep_time_minutes: int = Field(..., description="Preparation time in minutes", ge=0)
    cook_time_minutes: int = Field(..., description="Cooking time in minutes", ge=0)
    total_time_minutes: int = Field(..., description="Total time (prep + cook) in minutes", ge=0)
    
    # Servings
    servings: int = Field(..., description="Number of servings this recipe makes", gt=0)
    
    # Ingredients and instructions
    ingredients: List[Ingredient] = Field(..., description="List of ingredients needed")
    instructions: List[RecipeStep] = Field(..., description="Step-by-step cooking instructions")
    
    # Additional information
    dietary_tags: Optional[List[str]] = Field(None, description="Dietary tags (e.g., vegetarian, gluten-free, dairy-free, low-carb)")
    tips: Optional[List[str]] = Field(None, description="Cooking tips and suggestions")
    notes: Optional[str] = Field(None, description="Additional notes about the recipe")




# Grcoery List Model for structured output
class GroceryCategory(str, Enum):
    """Categories for organizing grocery items"""
    PRODUCE = "produce"
    DAIRY = "dairy"
    MEAT = "meat"
    SEAFOOD = "seafood"
    BAKERY = "bakery"
    PANTRY = "pantry"
    FROZEN = "frozen"
    BEVERAGES = "beverages"
    SNACKS = "snacks"
    CONDIMENTS = "condiments"
    OTHER = "other"

class GroceryItem(BaseModel):
    """Individual grocery item"""
    name: str = Field(..., description="Name of the grocery item")
    quantity: Optional[float] = Field(None, description="Quantity needed", ge=0)
    unit: Optional[str] = Field(None, description="Unit of measurement (e.g., lbs, oz, cups, count, bunch)")
    category: Optional[str] = Field(None, description="Category of the item for organization")
    estimated_price: Optional[float] = Field(None, description="Estimated price in dollars", ge=0)
    notes: Optional[str] = Field(None, description="Additional notes (e.g., 'organic', 'fresh', 'brand preference')")

class GroceryList(BaseModel):
    """Complete grocery list generated by LLM"""
    title: str = Field(..., description="Descriptive title for the grocery list")
    items: List[GroceryItem] = Field(..., description="List of grocery items to purchase")
    total_estimated_cost: Optional[float] = Field(None, description="Total estimated cost of all items", ge=0)
    dietary_preferences: Optional[List[str]] = Field(None, description="Dietary preferences this list accommodates (e.g., vegetarian, gluten-free)")
    serves: Optional[int] = Field(None, description="Number of people this grocery list serves", gt=0)
    notes: Optional[str] = Field(None, description="General notes about the grocery list")



# These save models our for the /recipes endpoint
class saveIngredient(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    name: str
    quantity: float
    unit: str
    notes: Optional[str] = None
    optional: bool = False
    location: Optional[str] = None
    category: Optional[str] = None

class saveRecipeStep(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    
    step_number: int
    instruction: str

class saveRecipe(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    
    id: Optional[int] = None
    title: str
    description: str
    cuisine: CuisineType
    meal_type: MealType
    difficulty: DifficultyLevel
    prep_time_minutes: int
    cook_time_minutes: int
    total_time_minutes: int
    servings: int
    ingredients: List[saveIngredient] = []
    instructions: List[saveRecipeStep] = []
    dietary_tags: Optional[List[str]] = None
    tips: Optional[List[str]] = None
    notes: Optional[str] = None
    created_at: Optional[datetime] = None

    @field_validator('cuisine', 'difficulty', 'meal_type', mode='before')
    @classmethod
    def normalize_enums(cls, v):
        if isinstance(v, str):
            return v.lower()
        return v

    @field_validator('dietary_tags', 'tips', mode='before')
    @classmethod
    def parse_json_strings(cls, v):
        # DB stores these as JSON strings, parse them back to lists
        if isinstance(v, str):
            try:
                return json.loads(v)
            except (json.JSONDecodeError, TypeError):
                return None
        return v


# Receipt scanning models
class MealPlanEntry(BaseModel):
    date: str = Field(..., description="ISO date YYYY-MM-DD — use exactly the date from the prompt")
    meal_type: str = Field(..., description="breakfast, lunch, dinner, or snack — match what was requested")
    recipe: Recipe = Field(..., description="Complete full recipe for this meal")


class DayPlanOutput(BaseModel):
    entries: List[MealPlanEntry] = Field(
        ...,
        description="One entry per requested meal_type. If 3 meal types were requested, return exactly 3 entries."
    )


class ReceiptItem(BaseModel):
    """A single food/grocery item extracted from a receipt"""
    name: str = Field(..., description="Name of the food or grocery item")
    quantity: Optional[float] = Field(None, description="Quantity if shown on receipt", gt=0)
    unit: Optional[str] = Field(None, description="Unit of measurement if identifiable (e.g. lbs, oz, count)")
    category: str = Field(
        ...,
        description="Category: one of Produce, Dairy & Eggs, Meat & Seafood, Grains & Bread, Pantry Staples, Beverages, Other"
    )

class ReceiptScanResult(BaseModel):
    """All food/grocery items extracted from a receipt image"""
    items: List[ReceiptItem] = Field(..., description="List of food and grocery items found on the receipt")