"""Initial migration - all tables

Revision ID: 7915f6f1160a
Revises: 
Create Date: 2026-03-18 22:23:17.966661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7915f6f1160a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('email', sa.String(), unique=True, nullable=False, index=True),
        sa.Column('username', sa.String(), unique=True, nullable=False, index=True),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('default_servings', sa.Integer(), default=4),
        sa.Column('dietary_restrictions', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('last_login', sa.DateTime(), nullable=True),
    )

    op.create_table(
        'recipes',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('title', sa.String(), nullable=False, index=True),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('cuisine', sa.String(), nullable=False),
        sa.Column('meal_type', sa.String(), nullable=False),
        sa.Column('difficulty', sa.String(), nullable=False),
        sa.Column('prep_time_minutes', sa.Integer(), nullable=False),
        sa.Column('cook_time_minutes', sa.Integer(), nullable=False),
        sa.Column('total_time_minutes', sa.Integer(), nullable=False),
        sa.Column('servings', sa.Integer(), nullable=False),
        sa.Column('dietary_tags', sa.Text(), nullable=True),
        sa.Column('tips', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('from_meal_plan', sa.Boolean(), default=False, nullable=False),
    )

    op.create_table(
        'recipe_ingredients',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('recipe_id', sa.Integer(), sa.ForeignKey('recipes.id'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('unit', sa.String(), nullable=False),
        sa.Column('notes', sa.String(), nullable=True),
        sa.Column('optional', sa.Boolean(), default=False),
        sa.Column('location', sa.String(), nullable=True),
        sa.Column('category', sa.String(), nullable=True),
    )

    op.create_table(
        'recipe_steps',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('recipe_id', sa.Integer(), sa.ForeignKey('recipes.id'), nullable=False),
        sa.Column('step_number', sa.Integer(), nullable=False),
        sa.Column('instruction', sa.Text(), nullable=False),
    )

    op.create_table(
        'pantry_items',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('quantity', sa.String(), nullable=True),
        sa.Column('unit', sa.String(), nullable=True),
        sa.Column('location', sa.String(), nullable=False, default='pantry'),
        sa.Column('category', sa.String(), nullable=False, default='Other'),
        sa.Column('added_at', sa.String(), nullable=True),
    )

    op.create_table(
        'grocery_lists',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('title', sa.String(), nullable=False, index=True),
        sa.Column('total_estimated_cost', sa.Float(), nullable=True),
        sa.Column('dietary_preferences', sa.Text(), nullable=True),
        sa.Column('serves', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
    )

    op.create_table(
        'grocery_items',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('grocery_list_id', sa.Integer(), sa.ForeignKey('grocery_lists.id'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('unit', sa.String(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('estimated_price', sa.Float(), nullable=True),
        sa.Column('notes', sa.String(), nullable=True),
    )

    op.create_table(
        'meal_plans',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('start_date', sa.String(), nullable=False),
        sa.Column('end_date', sa.String(), nullable=False),
        sa.Column('servings', sa.Integer(), nullable=False, default=2),
        sa.Column('created_at', sa.DateTime(), nullable=True),
    )

    op.create_table(
        'planned_meals',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('meal_plan_id', sa.Integer(), sa.ForeignKey('meal_plans.id'), nullable=False),
        sa.Column('date', sa.String(), nullable=False),
        sa.Column('meal_type', sa.String(), nullable=False),
        sa.Column('recipe_id', sa.Integer(), sa.ForeignKey('recipes.id'), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_meals')
    op.drop_table('meal_plans')
    op.drop_table('grocery_items')
    op.drop_table('grocery_lists')
    op.drop_table('pantry_items')
    op.drop_table('recipe_steps')
    op.drop_table('recipe_ingredients')
    op.drop_table('recipes')
    op.drop_table('users')
    # ### end Alembic commands ###
